# What {#sec-what}

We present the following guidelines to help you to complete the coursework assessment. If you have any questions, email Rob Davies at: `r.davies1@lancaster.ac.uk`

- You can read more about the motivations for the exercise, and the benefits to learning, in @sec-report-intro-why.
- You can read about ways -- methods -- to approach the exercise in @sec-how.

::: callout-important
Here we outline what we expect you to do.
:::

## What data can I analyse?

Students have taken a variety of approaches to the assignment (see @sec-how for a discussion of these options).

-   Some students choose to complete an analysis of a publicly available dataset, analyzed previously, data for which the report has been published in a journal article.
-   Some students choose to complete an analysis of a publicly available dataset that has been made available (for a report published as a data journal) but has not been analysed previously.
-   Some students choose to complete an analysis of one of the data-sets used for practical exercises in class: the example or demonstration data we collect together as the *curated data*.

## How will we evaluate reports?

The marks for the report will be depend primarily on the quality of the Results and Discussion sections of the report. 
This is because, in most cases, you will be using data for your analysis that were collected, previously, by other authors for an already published report. 

We cannot give you much credit for writing about the background research literature in the Introduction or about the Method of data collection because the authors of the original report did that work if you are using published data, or because Rob did that work if you are using demonstration data. 
We *can* give you credit for concisely and clearly summarizing the background research literature and method of data collection.

While we cannot give you much credit for the Introduction and Methods, we advise you that these sections will need to be effective in preparing the reader to:

- understand the nature of the research question(-s) or prediction(-s), their background and their motivation;
- understand the nature of the dataset analyzed, the measures taken, the participants or stimuli sampled;
- understand the motivation for, and the decision making involved in, the analysis approach adopted.

In short: what you write in the Introduction and Method sections will have function in making the results and Discussion effective.

We expect students to use one of the analysis methods taught in the module. 

::: callout-tip
Marks will be awarded depending:

-   on how appropriate the method is to the context, to the study design, to answering the research question, and to the features of the data;
-   on how effectively the analysis is explained -- students must explain the motivations for their decisions, explain their methods, and explain their findings effectively to gain points.
:::

Of course, some interests, datasets, or questions warrant the use of methods that are not taught but that students can learn independently.

::: callout-important
If you want to use a method that has not been taught in the module then you *must* discuss this first with Rob Davies.
:::

## How should reports be written?

You will prepare your report in the style of a short research article in the journal *Psychological Science*. You can view examples of articles [here](https://journals.sagepub.com/toc/PSS/current).

For the journal *Psychological Science*, a research article has to be written in a specific format with specific properties: we want something a bit different for this coursework, and we specify what we want here.

We require information about the background for the study, the research question, the hypotheses, the method of data collection, the method of data analysis, the results of the analysis, and the psychological interpretation of those results.

::: callout-important
- Word count limit: no more than **2000 words** are allowed for all materials.
- The reports should include abstract, introduction, methods, results, discussion and references sections, like most psychological research articles.
- Write in **complete sentences in full paragraphs**.
:::

## What structure should reports take?

The reports should include Abstract, Introduction, Methods, Results, Discussion and References sections, like a short research article in the journal *Psychological Science*.

The focus of marking will be on the quality of the Results and Discussion sections. 
Nevertheless, as explained, the Introduction and Method sections need to be effective so that the Results and Discussion sections can be effective.

One way to check that what you say in earlier sections is sufficient to prepare the reader for what they encounter in later sections is to write *forwards* and then review *backwards* through the text of your report.

::: callout-tip
1. Write *forwards*: enter information, as appropriate, progressing from Introduction to Methods to Results to Discussion.
2. Then, in review, work *backwards*: 

- Can the reader understand the Discussion given what was presented in the Results? 
- Can they understand the analysis, what you did, why and how, given the information in the Method? 
- Can they understand the Method, what the measures are, what was done, and why, given the motivations and aims explained in the Introduction?
:::

### Introduction and Method sections

Some general advice on what you need to communicate in the Introduction and Methods sections is that what you write in these sections should provide the reader with the information they need to answer the following questions:

1. **Introduction**

-   What did the researchers do and why did the researchers do it?
-   What was the question addressed in the study and why is it interesting?
-   What were the hypotheses or predictions?
-   What results were expected and how would they relate to the hypotheses?

2. **Method**

-   What was done to collect the data?
-   Who were tested (Participants)?
-   What materials were used in testing (Materials)?
-   What was the design of the study?
-   What procedure was used?

You will need to rely on your experience reading primary research articles to help you to judge *how much* information you need to present and *when* you need to present it.

::: callout-tip
If you are unsure, pick an article you admire in a journal and *analyze* how they present information, what they explain, and to what level of detail.
:::

### Results and Discussion sections

You must write text that explains to the reader what analysis you did, why you did it, what results you found, and what you think the implications of those results may be. 

::: callout-tip
Be clear on:

- what the outcome measure or dependent variable for analysis was,
- and what factors or predictor variables were brought into the analysis of that outcome
:::

You need to be clear about these things because the reader needs to understand these things well to be able to understand your results reporting.

You need to ensure that the text you write for the Results section provides the reader with the information they need to answer the following questions:-

3. **Results**

-   What hypotheses were tested?
-   What methods were used to test the hypotheses?
-   Why are they appropriate?
-   What were the results? What were the direction and relative size of effects?

Students often ask what analysis methods they can use.
The answer to that question depends on the question or hypothesis, the nature of the dataset, and the appropriateness of the different analysis options.

You can read a discuss of the nature of the choices open to any data analysis job in @sec-multiverse.
You can read about ways to identify how you can approach the analysis task in @sec-whatanalysis or @sec-try-multiverse.

::: callout-tip
- Do what seems reasonable using one or more of the analysis methods practiced in class
- And **explain your reasoning**
:::

If you use a dataset that is already published in a journal such as *Psychological Science*, then your presentation of the results may differ from the presentation in the article in ways that highlight new features of the data.
You may wish to identify the specific difference between the analysis you do and the analysis that was reported in the article that is the source for your data, if you derive your data from a published article, and if that article includes a statistical analysis.

It will help the reader and, sometimes, you if you indicate the source of the data and share your analysis code directly.

::: callout-tip
- If you get your data from a published article then you will cite that article but it may be helpful if, in the Method section, you add a link to the data repository (e.g. on OSF) so that your reader can access the data if necessary.
- Put the code for the analysis you do and report, with comments, in an Appendix. The appendix will not be counted towards word count limits.
:::

By the time the reader gets to the Discussion, they should be prepared for your outline of the questions or predictions, your identification of the main findings, and your critical evaluation of those findings, in context, and in relation to theoretical or practical implications.

You need to ensure that the text you write for the Discussion section enables the reader to understand the answer to the following questions:

4. **Discussion**

-   What are the theoretical implications of the study findings?
-   What are the practical implications?

You will understand that not every dataset can be analyzed in ways that have either or both theoretical or practical implications.

The main point is that you should keep in mind what the reader should get out of (what benefit) reading your report.

::: callout-tip
One way to think about the task for the Discussion is that you need to *make sense* of the results for the reader.
:::

You will want to:

- locate the ways in which your results fit into a wider (research or practice or theoretical) context;
- explain how the results do or do not add to or change understanding;
- explain if there are limitations in the data (maybe inherited from the source) or analysis;
- explain what future research may usefully do;
- identify the conclusions that can be drawn from the report.

::: callout-tip
Any or every analysis will have limitations so you would be well advised to be *selective* and *constructive*:

- *selective*: are the limitations you identify likely to affect or bias results? 
- *constructive*: in what ways would practicable future research address these limitations?
:::

Explaining implications or limitations is not a box to tick in this exercise so that you can say you have met a criterion for assessment.
This is an opportunity for you to work in a *scholarly* way and for you to present your work in a *scholarly* way.
This will require reflection, critical evaluation, and a grasp of elements of the relevant literature.

## Summary

Reports should present **enough information that the reader can understand**: 

- the background and motivation for a study; 
- the features of the data analyzed and the methods of data collection; 
- the approach taken in analysis, the analysis steps, and the results; 
- the relationship between the observed results and the expected results, and the interpretation of findings in relation to previous work. 

::: callout-tip
To be clear about clarity: 

- explain, spell things out (decisions, reasoning, interpretations) as if you were explaining them to a reasonably intelligent reader, a Psychologist who is not a specialist in the area of study occupied by the study reported, i.e. me. 
:::

## What format is required?

### Statistics, tables and figures should follow APA guidelines. See here for a free guide:

For general APA formatting of reports:

<https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_style_introduction.html>

And for APA formatting of statistics and numbers:

<https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/apa_numbers_statistics.html>

Though the APA guidelines are the authoritative guide.