<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Psychological data analysis for graduate students - 3&nbsp; Introduction to multilevel data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./02-mixed.html" rel="next">
<link href="./visualization.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction to multilevel data</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Psychological data analysis for graduate students</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Making the most of R</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./knowledge-ecosystem.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R knowledge</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visualization.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data visualization</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Models</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-multilevel.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction to multilevel data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-mixed.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Introduction to linear mixed-effects models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-mixed.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Developing linear mixed-effects models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-glmm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to Generalized Linear Mixed-effects Models</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Writing research reports</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction: the why</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./what.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">What</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">How</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">End</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-multi-motivations" id="toc-sec-multi-motivations" class="nav-link active" data-scroll-target="#sec-multi-motivations"><span class="toc-section-number">3.1</span>  Motivations</a>
  <ul class="collapse">
  <li><a href="#sec-multi-names" id="toc-sec-multi-names" class="nav-link" data-scroll-target="#sec-multi-names"><span class="toc-section-number">3.1.1</span>  A word about names</a></li>
  </ul></li>
  <li><a href="#sec-multi-challenges" id="toc-sec-multi-challenges" class="nav-link" data-scroll-target="#sec-multi-challenges"><span class="toc-section-number">3.2</span>  Challenges</a></li>
  <li><a href="#the-key-idea-to-get-us-started" id="toc-the-key-idea-to-get-us-started" class="nav-link" data-scroll-target="#the-key-idea-to-get-us-started"><span class="toc-section-number">3.3</span>  The key idea to get us started</a></li>
  <li><a href="#sec-multi-approach" id="toc-sec-multi-approach" class="nav-link" data-scroll-target="#sec-multi-approach"><span class="toc-section-number">3.4</span>  The approach we take</a></li>
  <li><a href="#sec-multi-targets" id="toc-sec-multi-targets" class="nav-link" data-scroll-target="#sec-multi-targets"><span class="toc-section-number">3.5</span>  Targets</a></li>
  <li><a href="#sec-multi-guide" id="toc-sec-multi-guide" class="nav-link" data-scroll-target="#sec-multi-guide"><span class="toc-section-number">3.6</span>  Study guide</a></li>
  <li><a href="#sec-multi-data-intro" id="toc-sec-multi-data-intro" class="nav-link" data-scroll-target="#sec-multi-data-intro"><span class="toc-section-number">3.7</span>  The data we will work with: Brazilian school children</a>
  <ul class="collapse">
  <li><a href="#sec-multi-data-download" id="toc-sec-multi-data-download" class="nav-link" data-scroll-target="#sec-multi-data-download"><span class="toc-section-number">3.7.1</span>  Locate and download the data file</a></li>
  <li><a href="#sec-multi-data-load" id="toc-sec-multi-data-load" class="nav-link" data-scroll-target="#sec-multi-data-load"><span class="toc-section-number">3.7.2</span>  Read in the data file – so that you can access the data – by using the load() function</a></li>
  <li><a href="#inspect-the-data" id="toc-inspect-the-data" class="nav-link" data-scroll-target="#inspect-the-data"><span class="toc-section-number">3.7.3</span>  Inspect the data</a></li>
  </ul></li>
  <li><a href="#tidy-the-data" id="toc-tidy-the-data" class="nav-link" data-scroll-target="#tidy-the-data"><span class="toc-section-number">3.8</span>  Tidy the data</a>
  <ul class="collapse">
  <li><a href="#select-the-variables" id="toc-select-the-variables" class="nav-link" data-scroll-target="#select-the-variables"><span class="toc-section-number">3.8.1</span>  Select the variables</a></li>
  <li><a href="#remove-missing-values" id="toc-remove-missing-values" class="nav-link" data-scroll-target="#remove-missing-values"><span class="toc-section-number">3.8.2</span>  Remove missing values</a></li>
  <li><a href="#getting-r-to-treat-a-variable-as-a-type-object-of-the-kind-required-using-the-as.numeric-function" id="toc-getting-r-to-treat-a-variable-as-a-type-object-of-the-kind-required-using-the-as.numeric-function" class="nav-link" data-scroll-target="#getting-r-to-treat-a-variable-as-a-type-object-of-the-kind-required-using-the-as.numeric-function"><span class="toc-section-number">3.8.3</span>  Getting R to treat a variable as a type object of the kind required – using the as.numeric() function</a></li>
  </ul></li>
  <li><a href="#introduction-to-multilevel-models" id="toc-introduction-to-multilevel-models" class="nav-link" data-scroll-target="#introduction-to-multilevel-models"><span class="toc-section-number">3.9</span>  Introduction to multilevel models</a>
  <ul class="collapse">
  <li><a href="#main-ideas-phenomena-and-data-sets-in-the-social-sciences-often-have-a-multilevel-structure" id="toc-main-ideas-phenomena-and-data-sets-in-the-social-sciences-often-have-a-multilevel-structure" class="nav-link" data-scroll-target="#main-ideas-phenomena-and-data-sets-in-the-social-sciences-often-have-a-multilevel-structure"><span class="toc-section-number">3.9.1</span>  Main ideas – Phenomena and data sets in the social sciences often have a multilevel structure</a></li>
  <li><a href="#multilevel-models-why-they-are-more-used-and-more-useful-than-traditional-methods" id="toc-multilevel-models-why-they-are-more-used-and-more-useful-than-traditional-methods" class="nav-link" data-scroll-target="#multilevel-models-why-they-are-more-used-and-more-useful-than-traditional-methods"><span class="toc-section-number">3.9.2</span>  Multilevel models – why they are more used and more useful than traditional methods</a></li>
  <li><a href="#practical-applications-children-sampled-within-classes" id="toc-practical-applications-children-sampled-within-classes" class="nav-link" data-scroll-target="#practical-applications-children-sampled-within-classes"><span class="toc-section-number">3.9.3</span>  Practical applications: children sampled within classes</a></li>
  <li><a href="#to-understand-the-application-of-multilevel-models-first-we-ignore-the-multilevel-structure-in-the-data" id="toc-to-understand-the-application-of-multilevel-models-first-we-ignore-the-multilevel-structure-in-the-data" class="nav-link" data-scroll-target="#to-understand-the-application-of-multilevel-models-first-we-ignore-the-multilevel-structure-in-the-data"><span class="toc-section-number">3.9.4</span>  To understand the application of multilevel models: first, we ignore the multilevel structure in the data</a></li>
  <li><a href="#a-linear-model-ignores-the-multilevel-structure-in-the-data" id="toc-a-linear-model-ignores-the-multilevel-structure-in-the-data" class="nav-link" data-scroll-target="#a-linear-model-ignores-the-multilevel-structure-in-the-data"><span class="toc-section-number">3.9.5</span>  A linear model ignores the multilevel structure in the data</a></li>
  <li><a href="#notation" id="toc-notation" class="nav-link" data-scroll-target="#notation"><span class="toc-section-number">3.9.6</span>  Notation</a></li>
  <li><a href="#can-we-really-ignore-the-multilevel-structure" id="toc-can-we-really-ignore-the-multilevel-structure" class="nav-link" data-scroll-target="#can-we-really-ignore-the-multilevel-structure"><span class="toc-section-number">3.9.7</span>  Can we really ignore the multilevel structure?</a></li>
  <li><a href="#linear-models-for-multilevel-data-dealing-with-the-hierarchical-structure" id="toc-linear-models-for-multilevel-data-dealing-with-the-hierarchical-structure" class="nav-link" data-scroll-target="#linear-models-for-multilevel-data-dealing-with-the-hierarchical-structure"><span class="toc-section-number">3.9.8</span>  Linear models for multilevel data – dealing with the hierarchical structure</a></li>
  <li><a href="#two-step-or-slopes-as-outcomes-linear-models-as-approximations-to-the-linear-mixed-effects-or-multilevel-modeling-approach" id="toc-two-step-or-slopes-as-outcomes-linear-models-as-approximations-to-the-linear-mixed-effects-or-multilevel-modeling-approach" class="nav-link" data-scroll-target="#two-step-or-slopes-as-outcomes-linear-models-as-approximations-to-the-linear-mixed-effects-or-multilevel-modeling-approach"><span class="toc-section-number">3.9.9</span>  Two-step or slopes-as-outcomes linear models as approximations to the Linear Mixed-effects or Multilevel modeling approach</a></li>
  <li><a href="#multilevel-models" id="toc-multilevel-models" class="nav-link" data-scroll-target="#multilevel-models"><span class="toc-section-number">3.9.10</span>  Multilevel models</a></li>
  <li><a href="#how-should-we-think-about-the-differences-between-the-classes" id="toc-how-should-we-think-about-the-differences-between-the-classes" class="nav-link" data-scroll-target="#how-should-we-think-about-the-differences-between-the-classes"><span class="toc-section-number">3.9.11</span>  How should we think about the differences between the classes?</a></li>
  <li><a href="#fitting-a-multilevel-model-using-the-lmer-function" id="toc-fitting-a-multilevel-model-using-the-lmer-function" class="nav-link" data-scroll-target="#fitting-a-multilevel-model-using-the-lmer-function"><span class="toc-section-number">3.9.12</span>  Fitting a multilevel model using the lmer() function</a></li>
  <li><a href="#reading-the-lmer-results" id="toc-reading-the-lmer-results" class="nav-link" data-scroll-target="#reading-the-lmer-results"><span class="toc-section-number">3.9.13</span>  Reading the <em>lmer</em> results</a></li>
  <li><a href="#fixed-and-random-effects" id="toc-fixed-and-random-effects" class="nav-link" data-scroll-target="#fixed-and-random-effects"><span class="toc-section-number">3.9.14</span>  Fixed and random effects</a></li>
  <li><a href="#is-there-a-difference-between-linear-model-and-linear-mixed-effects-model-results" id="toc-is-there-a-difference-between-linear-model-and-linear-mixed-effects-model-results" class="nav-link" data-scroll-target="#is-there-a-difference-between-linear-model-and-linear-mixed-effects-model-results"><span class="toc-section-number">3.9.15</span>  Is there a difference between linear model and linear mixed-effects model results?</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="toc-section-number">3.10</span>  Conclusions</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="toc-section-number">3.10.1</span>  Summary</a></li>
  <li><a href="#useful-functions" id="toc-useful-functions" class="nav-link" data-scroll-target="#useful-functions"><span class="toc-section-number">3.10.2</span>  Useful functions</a></li>
  </ul></li>
  <li><a href="#r-code-and-data-file-access-for-the-class" id="toc-r-code-and-data-file-access-for-the-class" class="nav-link" data-scroll-target="#r-code-and-data-file-access-for-the-class"><span class="toc-section-number">3.11</span>  R code and data file access for the class</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="toc-section-number">3.12</span>  References</a>
  <ul class="collapse">
  <li><a href="#sec-multi-reading" id="toc-sec-multi-reading" class="nav-link" data-scroll-target="#sec-multi-reading"><span class="toc-section-number">3.12.1</span>  Recommended reading</a></li>
  <li><a href="#references-list" id="toc-references-list" class="nav-link" data-scroll-target="#references-list"><span class="toc-section-number">3.12.2</span>  References list</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-intro-multilevel" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction to multilevel data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="cell">

</div>
<section id="sec-multi-motivations" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-multi-motivations"><span class="header-section-number">3.1</span> Motivations</h2>
<p>This week, we shall start to develop skills in using a method or approach that is essential in modern data analysis: <em>multilevel modeling</em>. We are going to invest four weeks in working on this approach. This investment is designed to give you a specific, important, advantage in your work as a psychologist, or as someone who produces or consumes psychological research.</p>
<div class="callout-advice callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Advice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Multilevel models: <em>why</em> do we need to do this? - Four weeks is a lot of time to spend on one method.</p>
</div>
</div>
<p>It is now clear that someone who works in psychological research <em>has</em> to know about multilevel or hierarchically structured data, and has to know how to apply multilevel models (or mixed-effects models). Growth in the popularity of these kinds of analysis has been very very rapid, as can be seen in <a href="#fig-meteyard-davies-2020-fig-5-lme-growth">Figure&nbsp;<span>3.1</span></a>. It is now, effectively, the standard or default method for professional data analysis in most areas of psychological and other social or clinical sciences (or it soon will be). There are good reasons for this <span class="citation" data-cites="Baayen2008">(<a href="references.html#ref-Baayen2008" role="doc-biblioref">Baayen et al., 2008</a>)</span>.</p>
<div id="fig-meteyard-davies-2020-fig-5-lme-growth" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="meteyard-davies-2020-fig-5-lme-growth.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3.1: Number of Pubmed citations for ‘Linear Mixed Models’ by year. Generated using the tool available at http://dan.corlan.net/medline-trend.html, entering “Linear Mixed Models” as the phrase search term and using data from 2000 to 2018, from Meteyard and Davies (2020) – used without permission</figcaption><p></p>
</figure>
</div>
<p>We continue to teach ANOVA and multiple regression (linear models) in our courses because the research literature is full of the results of analyses done using these methods and because many psychologists continue to use these methods in their research. However, there is increasingly wide-spread recognition that these classical methods have serious problems when applied to data with hierarchical structure. Because most psychological data (not all) will have hierarchical structure, this makes learning about multilevel or mixed-effects methods a key learning objective.</p>
<p>But, because it is relatively new, many professional psychologists struggle to understand why or how to use these methods effectively. This means that students who acquire the skill graduate with a clear <em>employability</em> advantage. It also means that we have to take seriously the challenge of learning about these methods. This is why we will spend a bit of time on them. In my experience, in over a decade of teaching multilevel models, in working with both students and professionals, we shall need to develop understanding and skills gradually. We will work patiently, so that we can secure understanding by building our learning through a series of practical examples, increasing the scope of our practical skills, and developing the sophistication of our understanding, step-by-step, as we go.</p>
<section id="sec-multi-names" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="sec-multi-names"><span class="header-section-number">3.1.1</span> A word about names</h3>
<p>Multilevel models are also known as hierarchical models or linear mixed-effects models or random effects models. People use these terms interchangeably. They also use the abbreviations LMMs or LMEs. Sorry about that: humans make methods, and the names we use for things do vary.</p>
<p>I will only use the terms <em>multilevel</em> or <em>linear mixed-effects</em> models.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>This week, we emphasize the multilevel perspective But, to anticipate future development, we will come to think in terms of mixed-effects models.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="sec-multi-challenges" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-multi-challenges"><span class="header-section-number">3.2</span> Challenges</h2>
<p>The key challenges for learning should be explained at the start so that we know what we shall have to do to overcome them.</p>
<ol type="1">
<li>Even though most psychological data has some sort of multilevel or hierarchical structure, we are not used to recognizing it. This is because the structure has often been hidden or ignored in the education and practice of traditional research methods in Psychology.</li>
</ol>
<p>In time, you will come to <strong>see multilevel structure everywhere</strong> <span class="citation" data-cites="kreft1998">(<a href="references.html#ref-kreft1998" role="doc-biblioref">Kreft &amp; Leeuw, 1998</a>)</span>. But first you will need to get some practice so that you can become familiar with the idea and learn to recognize what it looks like when data have a multilevel or hierarchical structure. This is why we will examine multilevel structured data across a range of different kinds of experiments or surveys, over a series of weeks.</p>
<p>We will learn to identify and understand hierarchical structure in psychological data by just looking at datasets, by producing visualizations, by doing analyses, and by trying to explain to ourselves and each other what we think we see.</p>
<ol start="2" type="1">
<li>The ideas that support an understanding of why and how we use multilevel models can be intimidating when we first encounter them. The mathematics behind how the models work <em>is</em> both profound and sophisticated. But the good news is that we can practice the application of the analysis method while talking and thinking about the critical ideas using just words or plots.</li>
</ol>
<p>We cannot or should not avoid engaging with the ideas – because we have to be able to explain what we are doing – but there are many routes to an effective understanding. For those who want to develop a more mathematically-based perspective, I will provide references to important texts in the literature on multilevel models (see <a href="#sec-multi-reading"><span>Section&nbsp;3.12.1</span></a>).</p>
</section>
<section id="the-key-idea-to-get-us-started" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="the-key-idea-to-get-us-started"><span class="header-section-number">3.3</span> The key idea to get us started</h2>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Multilevel models are a <em>general</em> form of linear model.</p>
</div>
</div>
<p>Another way of saying this is: <em>linear models are a special form of multilevel models</em>.</p>
<p>This is because linear models assume that observations are independent. We often cannot make this assumption, as we shall see. More generally, then, we do not assume that observations are independent and so we use multilevel models.</p>
</section>
<section id="sec-multi-approach" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-multi-approach"><span class="header-section-number">3.4</span> The approach we take</h2>
<p>We are <em>not</em> going to take a mathematical approach to learning about multilevel models. We do not have to. The approach we are going to take is:</p>
<ol type="1">
<li><strong>verbal</strong> – We will talk about the main ideas in words. Sometimes, we will present formulas but that is just to save having to use <em>too many</em> words.</li>
<li><strong>visual</strong> – We will show ourselves and each other what multilevel structure in data looks like, and what that structure means for our analyses of behaviour.</li>
<li><strong>practical</strong> – We will use R to complete analyses, so we will learn about coding models in practice. Fortunately, through coding we can get a clear idea of what we want the models to do.</li>
</ol>
</section>
<section id="sec-multi-targets" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sec-multi-targets"><span class="header-section-number">3.5</span> Targets</h2>
<p>Our learning objectives include the development of key concepts and skills.</p>
<ol type="1">
<li><strong>concepts</strong> – how data can have multilevel structures and what this requires in models</li>
<li><strong>skills</strong></li>
</ol>
<!-- -->
<ol type="i">
<li>use visualization to examine observations within groups</li>
<li>run linear models over all data and within each class</li>
<li>use the <code>lmer()</code> function to fit models of multilevel data</li>
</ol>
<p>We are just getting started. Our plan will be to build depth and breadth in understanding as we progress over the next few weeks.</p>
</section>
<section id="sec-multi-guide" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="sec-multi-guide"><span class="header-section-number">3.6</span> Study guide</h2>
<ol type="1">
<li>Read in the example data <code>BAFACALO_DATASET.RData</code> and identify how the data are structured at multiple levels.</li>
<li>Use visualizations to explore the impact of the structure.</li>
<li>Run analyses using linear models (revision) and linear mixed-effects models (extension) code.</li>
<li>Review readings provided.</li>
</ol>
</section>
<section id="sec-multi-data-intro" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="sec-multi-data-intro"><span class="header-section-number">3.7</span> The data we will work with: Brazilian school children</h2>
<p>This week, we will be working with data taken from a study on education outcomes in Brazilian children, reported by <span class="citation" data-cites="golino2014">Golino &amp; Gomes (<a href="references.html#ref-golino2014" role="doc-biblioref">2014</a>)</span>. First, we will progress through the steps required to download and prepare the files for analysis in R.</p>
<p>The <code>BAFACALO_DATASET.RData</code> data were collected and shared online by <span class="citation" data-cites="golino2014">Golino &amp; Gomes (<a href="references.html#ref-golino2014" role="doc-biblioref">2014</a>)</span>. Information about the background motivating the study, the methods of data collection, along with the dataset itself, can be found <a href="https://openpsychologydata.metajnl.com/articles/10.5334/jopd.af/">here</a>.</p>
<p><span class="citation" data-cites="golino2014">Golino &amp; Gomes (<a href="references.html#ref-golino2014" role="doc-biblioref">2014</a>)</span> collected school end-of-year subject grades for a sample of 292 children recruited from multiple classes in a school in Brazil. Here, each subject is a theme or course that children studied in school, e.g., Physics or English language, and for which each child was awarded a grade at the end of the school year. So, we have information on different children, and information about their subject grades. Children were taught in different classes but the classes appear to be units of the school organization (the information is not quite clear) not subject or course groupings. Thus, we also have information on which classes children were in when data about them were collected.</p>
<p>The data were compiled to an .RData format file.</p>
<p><code>.RData</code> is R’s own file format so the code you use to load and access the data for analysis is a bit simpler than you are used to. (You will have used <code>read.csv()</code> or <code>read_csv()</code> previously.)</p>
<p>In my own practice, I prefer to keep files in formats like <code>.csv</code> which can be opened and read in other software applications (like Excel), so using an <code>.RData</code> is an exception in these materials.</p>
<section id="sec-multi-data-download" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="sec-multi-data-download"><span class="header-section-number">3.7.1</span> Locate and download the data file</h3>
<p>You can access the data from the link associated with the <span class="citation" data-cites="golino2014">Golino &amp; Gomes (<a href="references.html#ref-golino2014" role="doc-biblioref">2014</a>)</span> article <a href="http://dx.doi.org/10.7910/DVN/23150">here</a>.</p>
<p>Or you can download the <a href="files/data-01-multilevel.zip">data-01-multilevel.zip</a> files folder for this chapter.</p>
<p>The file is located in a .zip folder called <code>data-01-multilevel</code>. The data file is collected together with the .R scripts:</p>
<ul>
<li><code>01-multilevel-workbook.R</code> the workbook you will need to do the practical exercises.</li>
<li><code>01-multilevel-workbook-answers.R</code> with answers to questions and code for exercises.</li>
</ul>
</section>
<section id="sec-multi-data-load" class="level3" data-number="3.7.2">
<h3 data-number="3.7.2" class="anchored" data-anchor-id="sec-multi-data-load"><span class="header-section-number">3.7.2</span> Read in the data file – so that you can access the data – by using the load() function</h3>
<p>You can read the <code>BAFACALO_DATASET.RData</code> file into the R workspace or environment using the following code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"BAFACALO_DATASET.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="inspect-the-data" class="level3" data-number="3.7.3">
<h3 data-number="3.7.3" class="anchored" data-anchor-id="inspect-the-data"><span class="header-section-number">3.7.3</span> Inspect the data</h3>
<p>The dataset consists of rows and columns. Take a look. If you have successfully loaded the dataset into the R environment, then you should be able to view it.</p>
<p>You could look at the dataset by using the <code>View()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(BAFACALO_DATASET)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Or you can use the <code>head()</code> function to see the top few rows of the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(BAFACALO_DATASET)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  participant_id scholarity_father scholarity_mother household_income
1              1                NA                NA               NA
2              2                 1                 1                2
3              3                 3                 3                2
4              4                 1                 3                3
5              5                 2                 2                1
6              6                 1                 1                1
  class_number previous_school_type sex age VZi01 VZi02 VZi03 VZi04 VZi05 VZi06
1         &lt;NA&gt;                   NA  NA  NA     1     1     1     1     1     1
2         &lt;NA&gt;                   NA  NA  NA     1     1     1     1     1     0
3          M15                    2   0  16     1     1     0     1     0     1
4          M14                    2   1  14     1     1     1     1     1     1
5          M23                    2   0  17     1     1     1     1     1     1
6          M21                    2   1  17     1     1     1     1     1     1
  VZi07 VZi08 VZi09 VZi10 VZi11 VZi12 VZi13 VZi14 VZi15 VZi16 VZi17 VZi18 VZi19
1     0     1     1     1     1     1     0     0     1     1     0     1     1
2     0     1     1     1    NA    NA     0    NA    NA    NA    NA    NA    NA
3     0     1     0     1     1     1     1     0     1     1     1     1     1
4     1     1     1     1     1     1     1     1     1     1     1     1     1
5     0     1     0     1     1     1     0     0     1     1     0     1     1
6     1     1     1     1    NA     1    NA    NA     1     1     1     1     1
  VZi20 VZi21 VZi22 VZi23 VZi24 VZi25 VZi26 VZi27 VZi28 VZi29 VZi30 CFi01 CFi02
1     0     1     1     1     1     1     0     0     1     1     1     0     0
2    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA     0     0
3     1     0     1     0     1     1     0     1     1     1     1     1     1
4     1     1     1     1     1     1     1     1     1     1     1     1     1
5     0     1     1     0     0     1    NA     1    NA    NA    NA     1     1
6     0     1     1     1     1     1    NA    NA    NA    NA    NA     1     1
  CFi03 CFi04 CFi05 CFi06 CFi07 CFi08 CFi09 CFi10 CFi11 CFi12 CFi13 CFi14 CFi15
1     0     0     0     0     0     0     0     0     0     0     0     0     0
2     1     1     0    NA    NA    NA     1     0     1     0    NA    NA    NA
3     1     1    NA     1     1     1     1     1     1    NA     1     1     1
4     1     1     1     1     1     1     1     1     1     1     1     1     1
5     1     1     1    NA    NA    NA     1     0     1     1     0    NA    NA
6     1     1     1     1     1     1     1     1     1     1     1     1     1
  CFi16 CFi17 CFi18 CFi19 CFi20 CFi21 CFi22 CFi23 CFi24 CFi25 CFi26 CFi27 CFi28
1     0     0     0     0     0     0     0     0     0     0     0     0     0
2    NA     1     1     1    NA    NA    NA    NA     1     1     1     0     0
3     1     1     1     1     1     1     1     1     1     1     1     1     1
4     1     1     1     1     1     1     1     1     0     1     1     1     1
5    NA     1     1     1     0     1    NA    NA    NA     1     1     1     1
6     1     1     1     1     1     1     1     1     1     1     1     1     1
  CFi29 CFi30 CFi31 CFi32 V1i01 V1i02 V1i03 V1i04 V1i05 V1i06 V1i07 V1i08 V1i09
1     0     0     0     0     1     1     1     1     1     1     1     0     0
2    NA    NA    NA    NA     0     1     0     1     1     0     0     0     0
3     1     1     1     1     1     0     1     0     1     0     0     0     1
4     0     1     1     1     1    NA     1     0     1    NA    NA    NA    NA
5     0    NA    NA    NA     0     1    NA     1     1    NA    NA    NA    NA
6     1     1     1     1     1    NA     1     0     1     1    NA     1     1
  V1i10 V1i11 V1i12 V1i13 V1i14 V1i15 V1i16 V1i17 V1i18 V1i19 V1i20 V1i21 V1i22
1     1     0     1     1     1     1     0     1     1     1     0     0     0
2     1     0     1     1     1     1     0     1     0     0     0     1     0
3     1     0     0     0     1     1     1     1     0     0     0     0     0
4     0    NA    NA    NA     1     1    NA    NA    NA     1    NA    NA    NA
5    NA    NA     0    NA     1     1    NA     1     1     1    NA    NA     0
6     1     1     1    NA     1     1    NA     1     1     1     0    NA     0
  V1i23 V1i24 V2i01 V2i02 V2i03 V2i04 V2i05 V2i06 V2i07 V2i08 V2i09 V2i10 V2i11
1     1     1     0     1     0     0    NA    NA     0     1     1     0     0
2     1     1     0     0    NA     1    NA     0     0     1     1     1     0
3     1     0     0     1     1    NA    NA     0     1     0     0     0     1
4    NA    NA    NA    NA     1    NA    NA    NA    NA    NA     1    NA    NA
5     0    NA    NA    NA     0    NA    NA    NA     1     1     1    NA    NA
6     0    NA    NA     1     1    NA    NA    NA     0    NA     1    NA     0
  V2i12 V2i13 V2i14 V2i15 V2i16 V2i17 V2i18 V3i01 V3i02 V3i03 V3i04 V3i05 V3i06
1     0     0     1    NA    NA     0    NA     0     1     0     1     1     1
2     0     0     0    NA    NA     0     1     1     0     0     1    NA     0
3     0     0     0     0     0     0     0     1     1     0     1     1     1
4    NA    NA     1    NA    NA    NA    NA     1     0     1     1    NA    NA
5    NA    NA     1    NA    NA    NA    NA     1     1     0     1     1    NA
6     1    NA     1    NA    NA    NA    NA     1     1     0     1     1    NA
  V3i07 V3i08 V3i09 V3i10 V3i11 V3i12 V3i13 V3i14 V3i15 V3i16 V3i17 V3i18
1     1     1     0     0     0     0     0     0     1     1     0     1
2     0     0    NA    NA     1     1     0     1     1     1     1     0
3     0     0     0     0     0     1     0     1     0     1     1     1
4    NA    NA    NA    NA    NA    NA    NA    NA    NA     0     1    NA
5    NA    NA    NA    NA    NA     1    NA    NA    NA     0     1     0
6    NA    NA    NA    NA     1     1    NA     1     0     1     1     1
  MA1i01 MA1i02 MA1i03 MA1i04 MA1i05 MA1i06 MA1i07 MA1i08 MA1i09 MA1i10 MA1i11
1      0     NA      0      0     NA     NA     NA     NA     NA     NA     NA
2     NA     NA     NA      1     NA      0     NA     NA     NA      1      0
3      0      1      1      1      1      1      1      1      1      1      1
4      1      1      0      1      1      1      1      1      1      1      1
5      1      1      1      1      1      1      0      0      0      1      1
6      0      1      0      1      1      1      0      1      1      1      1
  MA1i12 MA1i13 MA1i14 MA1i15 MA2i01 MA2i02 MA2i03 MA2i04 MA2i05 MA2i06 MA2i07
1      1      1     NA     NA      1     NA     NA     NA     NA     NA     NA
2      1      0      1      0     NA      0     NA     NA     NA     NA     NA
3      1      1      1     NA      1      1      1      1      1      1      1
4      1      0      1      1      1      1      1      1      1      1      1
5      1      1      1      1      1      1      1      1      1      1      1
6      1      1      0      1      1     NA      1      1     NA     NA      1
  MA2i08 MA2i09 MA2i10 MVi01 MViO2 MViO3 MVi02 MViO4 MViO5 MVi03 MViO6 MViO7
1      1      0     NA     0     1     0     1    NA     1     0     1     1
2      0      1     NA     1     0     1     0    NA     1    NA     1     1
3      1      1     NA     1     1     1     0     1     1     1     1     1
4      0      1      1     1     1     1     1     1    NA     1     1     1
5      1      1      1     1     1     1     1     1     1     1     1     1
6      1     NA      1     1     1     1     1     1     1     1     1     1
  MVi04 MViO8 MViO9 RGi01 RGi02 RGi03 RGi04 RGi05 RGi06 RGi07 RGi08 RGi09 RGi10
1    NA     0     1    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2     1     0    NA     1     0     0     0     1     0    NA     1    NA    NA
3     1     0     1     1     1     1     1     1    NA     1     0     0    NA
4     1     1     1     1     1     1    NA     1     1     1     1     1     1
5     1     1     1     0     1     1     0     1     1     0    NA     1    NA
6     1     1     1     1     1     1     1     1     1     1     1     1     1
  RGi11 RGi12 RGi13 RGi14 RGi15 RLi01 RLi02 RLi03 RLi04 RLi05 RLi06 RLi07 RLi08
1    NA    NA    NA    NA    NA     1     1     1     1     0     1     1     0
2    NA    NA    NA    NA    NA     1     1     0     1    NA     1     1     1
3    NA    NA    NA    NA    NA     1     1     1     1     0     0     1     1
4     1     1     0     1     1     1     1     1     1     0     1     0     1
5     1     1    NA    NA    NA     1     1     1     1     1     1     0     1
6     1     0    NA     1     1     1     1     1     1     0     1     1     0
  RLi09 RLi10 RLi11 RLi12 RLi13 RLi14 RLi15 RLi16 RLi17 RLi18 RLi19 RLi20 RLi21
1     1     1     0     0     0     1     1     1     0     1     1     0     1
2     0     0     0     0     1     0     0     1     0     1     0     0     1
3     1     1     1     0     0     0     0     1     0     1     0     0     1
4     1     0     1     0     0     0     1     1     0     1     0     0     1
5     1     1     1     1     1     0     0     1     0     1     1     1     1
6     1     0     1     1     0     1     0     1     1     1     1    NA     1
  RLi22 RLi23 RLi24 RLi25 RLi26 RLi27 RLi28 RLi29 RLi30 Ii01 Ii02 Ii03 Ii04
1     0     1     0     0     0     1     1     1     0    1    1    1    1
2     1     1     0     1     0     1     0     0     0   NA    1   NA    0
3     0     1     1     0     0     1     1     1     0    1   NA    1    1
4     0     1     0     1     1     1     1     0     1    1   NA    1    1
5     0     1     0     0     0     1     1     0     1    1    1    1    1
6     1     1    NA    NA    NA    NA    NA    NA    NA    1    1    1   NA
  Ii05 Ii06 Ii07 Ii08 Ii09 Ii10 Ii11 Ii12 Ii13 Ii14 Ii15  N P1 P2   P3 FI1 FI2
1    1    1    1   NA    1   NA   NA   NA   NA   NA   NA NA NA NA &lt;NA&gt;  NA  NA
2   NA   NA    0   NA   NA   NA   NA   NA   NA   NA   NA NA NA NA &lt;NA&gt;  NA  NA
3    1    0    1    1    1    1    1    1    0    1   NA 35 25 22   40   9  12
4    1    1    1    1    1    1    1   NA   NA    0   NA 43 24 25   47  30  16
5    1    1   NA    1    1    1    0   NA   NA   NA   NA 39 27 22   33   9   9
6    1    1    1    1    1    1    1   NA   NA   NA   NA 38 34 23   44  14  11
  FF portuguese english math biology physics chimestry geography history
1 NA       &lt;NA&gt;    &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;    &lt;NA&gt;
2 NA       &lt;NA&gt;    &lt;NA&gt; &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;      &lt;NA&gt;      &lt;NA&gt;    &lt;NA&gt;
3 17         72    78.5 60.1    62.6    65.8      68.3        61    &lt;NA&gt;
4 15         62    81.5 85.5    72.2    77.7        90      65.5    &lt;NA&gt;
5  9         77      74   75      77      69      83.5      &lt;NA&gt;    81.5
6  9         82      96   92    91.6      80        91      &lt;NA&gt;      85</code></pre>
</div>
</div>
<p>You can check for yourself that each row holds data about a child, including their participant identity code, as well as information about their parents, household, gender, age, school class, and their grades on end-of-year subject attainment (e.g., how well they did in English language).</p>
<p>There are many more variables in the dataset than we need for our exercises, and a summary would fill pages of this chapter. You can see for yourself if you inspect the dataset using</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(BAFACALO_DATASET)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="tidy-the-data" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="tidy-the-data"><span class="header-section-number">3.8</span> Tidy the data</h2>
<p>When you inspect the file, you will see that it includes a large number of variables, but we only really care about those we will use in our exercises:</p>
<p>You can see that I am not explaining the variables in great depth. For our aims, we do not need more detailed information but please do read the data article if you wish to find out more.</p>
<p>We need to tidy the data before we can get to the analysis parts of this chapter. We are going to:</p>
<p>We shall need the <code>tidyverse</code> library of functions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="select-the-variables" class="level3" data-number="3.8.1">
<h3 data-number="3.8.1" class="anchored" data-anchor-id="select-the-variables"><span class="header-section-number">3.8.1</span> Select the variables</h3>
<p>We can start by selecting the variables we want, which include those named here, ignoring all the rest. We take the <code>BAFACALO_DATASET</code>. We then use the <code>select()</code> function to select the variables we want. And, lastly, we inspect the data using <code>summary()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>brazil <span class="ot">&lt;-</span> BAFACALO_DATASET <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">select</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                      class_number, participant_id,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                      portuguese, english, math, physics</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                      )</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(brazil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  class_number participant_id     portuguese     english         math    
 M11    : 21   Min.   :  1.00   60     : 10   100    : 17   60     : 13  
 M15    : 20   1st Qu.: 73.75   76     :  9   79     : 11   69     :  9  
 M14    : 19   Median :146.50   65     :  8   96     :  8   70     :  9  
 M36    : 19   Mean   :146.50   73     :  8   81     :  7   62     :  8  
 M18    : 18   3rd Qu.:219.25   74     :  7   89     :  7   71     :  7  
 (Other):133   Max.   :292.00   (Other):188   (Other):180   (Other):184  
 NA's   : 62                    NA's   : 62   NA's   : 62   NA's   : 62  
    physics   
 60     : 16  
 60.1   :  5  
 0      :  4  
 61.8   :  4  
 66     :  4  
 (Other):197  
 NA's   : 62  </code></pre>
</div>
</div>
<section id="code-tip" class="level4" data-number="3.8.1.1">
<h4 data-number="3.8.1.1" class="anchored" data-anchor-id="code-tip"><span class="header-section-number">3.8.1.1</span> Code tip</h4>
<p>Notice the code is written to create the new selected dataset and, at the same time, gave it a more usable (shorter) name, with ::::::::::::::::::::::::::</p>
</section>
</section>
<section id="remove-missing-values" class="level3" data-number="3.8.2">
<h3 data-number="3.8.2" class="anchored" data-anchor-id="remove-missing-values"><span class="header-section-number">3.8.2</span> Remove missing values</h3>
<p>If you look at the results of the selection, you can see that there are missing values, written as e.g.&nbsp;<code>NA's 62</code> at the bottom of each summary of each variable (if a variable column includes missing values). (Remember that in R <code>NA</code> means “not available” i.e.&nbsp;missing.) We will need to get rid of the missing values. It is simpler to do this at the start rather than wait for an error message, later, when some arithmetic function tells us it cannot give us a result because there are <code>NAs</code> present.</p>
<p>We can get rid of the missing values using <code>na.omit()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>brazil <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(brazil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you then look at a summary of the data again then you will see that the <code>NAs</code> are gone.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(brazil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  class_number participant_id    portuguese     english         math    
 M11    : 21   Min.   :  3.0   60     : 10   100    : 17   60     : 13  
 M15    : 20   1st Qu.: 77.5   76     :  9   79     : 11   69     :  9  
 M14    : 19   Median :144.5   65     :  8   96     :  8   70     :  9  
 M36    : 19   Mean   :146.6   73     :  8   81     :  7   62     :  8  
 M18    : 18   3rd Qu.:222.8   74     :  7   89     :  7   71     :  7  
 M21    : 17   Max.   :291.0   82     :  7   86     :  6   66     :  6  
 (Other):116                   (Other):181   (Other):174   (Other):178  
    physics   
 60     : 16  
 60.1   :  5  
 0      :  4  
 61.8   :  4  
 66     :  4  
 74.2   :  4  
 (Other):193  </code></pre>
</div>
</div>
</section>
<section id="getting-r-to-treat-a-variable-as-a-type-object-of-the-kind-required-using-the-as.numeric-function" class="level3" data-number="3.8.3">
<h3 data-number="3.8.3" class="anchored" data-anchor-id="getting-r-to-treat-a-variable-as-a-type-object-of-the-kind-required-using-the-as.numeric-function"><span class="header-section-number">3.8.3</span> Getting R to treat a variable as a type object of the kind required – using the as.numeric() function</h3>
<p>But if you look closely at the output from <code>summary(brazil)</code> you will see that the <code>portuguese</code> and <code>english</code> variables are summarized in the way that R summarizes factors. When you ask R to summarize factors, R gives you a count of the number of observations associated with each factor level, that is, each category in each variable. Here, it is treating a grade score like <span class="math inline">\(100\)</span> in <code>english</code> as a category (like you might treat <span class="math inline">\(dog\)</span> as a category of pets), and you can see that the count shows you that 17 children were recorded as having scored 100 in their class. We do not want numeric variables like subject grades (e.g.&nbsp;children’s grades in English) treated as categorical variables, factors.</p>
<p>You can also see that R gives you a numeric summary of the recorded values in the <code>participant_id</code> variable. This makes no sense because the identity code numbers are (presumably) assigned at random so identity numbers provide no useful numeric information for us. We do not want this either.</p>
<p>We want R to treat the educational attainment scores as numbers, and we can do this using the <code>as.numeric()</code> function. We want R to treat the class and participant identity numbers as factors (categorical variables), and we can do this using the <code>as.factor()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># -- change the variable types: coercion</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>brazil<span class="sc">$</span>portuguese <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(brazil<span class="sc">$</span>portuguese)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>brazil<span class="sc">$</span>english <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(brazil<span class="sc">$</span>english)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>brazil<span class="sc">$</span>math <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(brazil<span class="sc">$</span>math)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>brazil<span class="sc">$</span>physics <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(brazil<span class="sc">$</span>physics)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>brazil<span class="sc">$</span>class_number <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(brazil<span class="sc">$</span>class_number)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>brazil<span class="sc">$</span>participant_id <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(brazil<span class="sc">$</span>participant_id)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># -- inspect the data:</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(brazil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  class_number participant_id   portuguese       english           math       
 M11    : 21   3      :  1    Min.   : 1.00   Min.   : 1.00   Min.   :  1.00  
 M15    : 20   4      :  1    1st Qu.:26.25   1st Qu.:29.00   1st Qu.: 39.00  
 M14    : 19   5      :  1    Median :42.00   Median :55.00   Median : 58.00  
 M36    : 19   6      :  1    Mean   :43.55   Mean   :50.25   Mean   : 58.17  
 M18    : 18   7      :  1    3rd Qu.:58.75   3rd Qu.:73.00   3rd Qu.: 79.75  
 M21    : 17   9      :  1    Max.   :83.00   Max.   :93.00   Max.   :104.00  
 (Other):116   (Other):224                                                    
    physics      
 Min.   :  1.00  
 1st Qu.: 34.00  
 Median : 71.50  
 Mean   : 71.57  
 3rd Qu.:107.75  
 Max.   :148.00  
                 </code></pre>
</div>
</div>
<p>If you now look at the summary of the data, you can see that R will give you mean etc. for the subject or class score variables, showing that it is now treating them as numeric variables. In comparison, R gives you counts of the numbers of observations for each level (category) of categorical or nominal variables like <code>participant_id</code>.</p>
<section id="coercion-a-quick-lesson" class="level4" data-number="3.8.3.1">
<h4 data-number="3.8.3.1" class="anchored" data-anchor-id="coercion-a-quick-lesson"><span class="header-section-number">3.8.3.1</span> Coercion: a quick lesson</h4>
<p>R treats things like variables as vectors. A vector can be understood to be a set or list of elements, things like numbers of words.</p>
<p>R gives each vector a type (factor, numeric etc.) which helps to inform different functions how to handle that vector. Usually, R assigns type correctly but sometimes it does not. We can use what is called <em>coercion</em> to force R to assign the correct type to a variable.</p>
<p>It is more efficient to do this at the start. Normally, I would use <code>read_csv()</code> from <code>tidyverse</code> and assign type to variable using <code>col_types()</code> specification. See here for more information and an example:</p>
<p></p>
<p>But it is useful to learn what you need to do if you need to change the way a variable is treated after you have got the data into the R environment.</p>
</section>
<section id="exercise-experiment-with-coercion" class="level4" data-number="3.8.3.2">
<h4 data-number="3.8.3.2" class="anchored" data-anchor-id="exercise-experiment-with-coercion"><span class="header-section-number">3.8.3.2</span> Exercise – experiment with coercion</h4>
<p>In R, there are a family of functions that work together. You can test whether a variable (a vector, technically) is or is not a certain type using the <code>is.[something]</code> function. For example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(brazil<span class="sc">$</span>english)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">is.numeric</span>(brazil<span class="sc">$</span>english)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">is.character</span>(brazil<span class="sc">$</span>english)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And you can coerce variables so that they are treated as of certain types.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>brazil<span class="sc">$</span>english <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(brazil<span class="sc">$</span>english)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>brazil<span class="sc">$</span>english <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(brazil<span class="sc">$</span>english)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>brazil<span class="sc">$</span>english <span class="ot">&lt;-</span> <span class="fu">as.character</span>(brazil<span class="sc">$</span>english)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="introduction-to-multilevel-models" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="introduction-to-multilevel-models"><span class="header-section-number">3.9</span> Introduction to multilevel models</h2>
<section id="main-ideas-phenomena-and-data-sets-in-the-social-sciences-often-have-a-multilevel-structure" class="level3" data-number="3.9.1">
<h3 data-number="3.9.1" class="anchored" data-anchor-id="main-ideas-phenomena-and-data-sets-in-the-social-sciences-often-have-a-multilevel-structure"><span class="header-section-number">3.9.1</span> Main ideas – Phenomena and data sets in the social sciences often have a multilevel structure</h3>
<p>We (Psychologists) often adopt <em>Repeated Measures</em> or <em>Clustered</em> designs in our studies, and these designs yield data that have a multilevel structure. Examples of research which results in data with a multilevel structure include:</p>
<p>The key insight to keep in mind when considering the analysis of such data is that observations are clustered and are <em>not independent</em>. They are correlated. What is correlated with what?</p>
<p>Imagine testing a number of subjects by giving them all the same test. In that test, you might present them all with the same stimuli over a series of trials, so that everybody sees the same set of stimuli. Do you think an observed response recorded for any one individual will be uncorrelated i.e.&nbsp;independent of that person’s other responses? People are different and one usually finds that a slow or inaccurate subject is slow or inaccurate for most of their responses. That means that if you have information about one of their responses you can predict, in part, what the time or accuracy of one of their other responses would be. That capacity to predict one response from another is what we mean when we talk about a lack of independence.</p>
<p>Alternatively, imagine going to test children in a school. Will the children in one class be more like each other than they are like children in other classes? In other words, is there an effect of class – maybe due to the approach of the teacher, the effect of the class environment etc. – so that outcomes for children in a class are correlated with each other? We are talking, here, about a really quite general property of data collected in certain, very widely used, designs in Psychology: the <em>clustering or hierarchical ordering</em> of data.</p>
<p>This week, we will see that we must deal with the dependence of observations within a class, where the observed responses were made about the different pupils tested in a class, for a number of different classes.</p>
</section>
<section id="multilevel-models-why-they-are-more-used-and-more-useful-than-traditional-methods" class="level3" data-number="3.9.2">
<h3 data-number="3.9.2" class="anchored" data-anchor-id="multilevel-models-why-they-are-more-used-and-more-useful-than-traditional-methods"><span class="header-section-number">3.9.2</span> Multilevel models – why they are more used and more useful than traditional methods</h3>
<p>The utility of <strong>multilevel models</strong> to analyze <strong>multilevel data</strong> or hierarchically structured data is well established in education. In educational research, we often need to think about effects of interventions or correlations in the context of observing children in classes, schools or districts, perhaps over time or at different time points. This means that many of the critical textbooks present examples that are based on educational research data (Bryk &amp; Raudenbush, 1992; Goldstein, 2011; Kreft &amp; de Leeuw, 1998; Snijders &amp; Bosker, 2012).</p>
<p>Multilevel models are growing in popularity in Psychology as well as in Education because they can be used to account for systematic and random sources of variance in observed outcomes when data are hierarchically structured. A hierarchical structure is present in data when a researcher: tests participants who belong to different groups like classes, clinics or schools; presents a sample of stimuli to each member of a sample of participants; or makes repeated observations for each participant over a series of test occasions.</p>
<p>In these circumstances, the application of traditional analytic methods has typically required the researcher to aggregate their data (e.g., averaging the responses made by a participant to different stimuli) or to ignore the hierarchical structure in their data, (e.g., analyzing the responses made by some pupils while ignoring the fact that the pupils were tested in different classes). But the application of traditional analysis approaches (e.g., regression, ANOVA) to multilevel structured data extracts scientific costs (Baayen et al., 2008; Barr, Levy, Scheepers, &amp; Tily, 2013).</p>
<p>Ignoring structure by ignoring or averaging over sources of variability like differences between classes, participants, or stimulus items can mean that analyses are less sensitive because they fail to fully account for error variance. Where differences between classes, participants or stimuli include variation in the impact of experimental variables, e.g., individual differences in response to an experimental manipulation, the application of traditional methods can be associated with an increased risk of false positives in discovery. Yet these costs need no longer be suffered because the capacity to perform multilevel modeling is now readily accessible.</p>
</section>
<section id="practical-applications-children-sampled-within-classes" class="level3" data-number="3.9.3">
<h3 data-number="3.9.3" class="anchored" data-anchor-id="practical-applications-children-sampled-within-classes"><span class="header-section-number">3.9.3</span> Practical applications: children sampled within classes</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="LME-multistage-sample-snijders-fig2-1.png" class="img-fluid figure-img" style="width:55.0%"></p>
<p></p><figcaption class="figure-caption">Snijders and Bosker (2012) Multistage sample – used without permission</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>If a researcher tests participants belonging to different groups, e.g., records the educational attainment of different children recruited from different classes in a school, the test scores for the participants are observations that occupy the lowest level of a hierarchy. In multilevel modeling, those observations are understood to be nested within higher-level sampling units, here, the classes. We can say that the children are sampled from the population of children. And the classes are sampled from the population of classes. Critically, we recognize that the children’s test scores are <strong>nested within the classes</strong>.</p>
<p>Figure @ref(fig:SB12multistage) presents a schematic of this kind of multi-stage sampling (from Snijders and Bosker, 2012). What the figure shows you is that psychologists often first sample groups (shown as big rectangles or squares) like schools or classes and then sample individuals within the groups (shown as small circles or squares). This multi-stage sampling has important consequences, as we shall see.</p>
<p>We are going to be working with the school data collected by Golino and Gomes (2014) in Brazil, so let’s take another look at that dataset. Figure @ref(fig:SB12multistage) presents the first 25 rows of the selected-variables <code>brazil</code> dataset. (I have arranged the rows by class number ID.) You can see that there are multiple rows of data for each <code>class_number</code>, one row for each child, with multiple children (you can see different <code>participant_id</code> numbers). This presentation of the dataset illustrates in practical terms – what you can actually see when you look at your data – what the schematic Figure @ref(fig:SB12multistage) shows in conceptual terms.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   class_number participant_id portuguese english math physics
1           M36             11         80      55   60      81
2           M36             30         48      55   43      57
3           M36             93         83      75   55      80
4           M36             95         80      66   55      66
5           M36            111         80      57   99     129
6           M36            117         27      76   83      89
7           M36            153          2      66   89     141
8           M36            163         68      88   74     137
9           M36            176         80      75   60     127
10          M36            216         75      79   64     124
11          M36            223         81      56   58      78
12          M36            234         81      75   49      74
13          M36            242         81      67   45      77
14          M36            254         76      51   33     103
15          M36            260         81      59   39      82
16          M36            271         64      69   82     138
17          M36            278         80      57   56     107
18          M36            280         83      64   56      84
19          M36            286         80      91   64      98
20          M35             20         42      61   97      92
21          M35            118         33      59   33      80
22          M35            140         28      40   33      58
23          M35            179         38      69   56     145
24          M35            247         65      51   64      97
25          M33             15         76      70   73      85</code></pre>
</div>
</div>
</section>
<section id="to-understand-the-application-of-multilevel-models-first-we-ignore-the-multilevel-structure-in-the-data" class="level3" data-number="3.9.4">
<h3 data-number="3.9.4" class="anchored" data-anchor-id="to-understand-the-application-of-multilevel-models-first-we-ignore-the-multilevel-structure-in-the-data"><span class="header-section-number">3.9.4</span> To understand the application of multilevel models: first, we ignore the multilevel structure in the data</h3>
<p>Recognizing that the children’s data are observed within classes means that, when we examine the factors that influence variance in observed outcomes, we need to take into account the fact that the children can be grouped by (or under) the class they were in when their grades were recorded. We can develop an understanding of what this means by moving through a series of steps.</p>
<p>To illustrate the understanding we need to develop, we analyze the end-of-year school subject grades for the sample of 292 children studied by Golino and Gomes (2014). With these data, we can examine whether differences between children in their Portuguese language grades predicts differences in their English language grades. (We don’t have a theoretical reason to make this prediction though it does not seem unreasonable.) Let’s make this our research question.</p>
<p>Now, the first step we take in our development of understanding will be to <em>first ignore</em> the importance of the potential differences between classes.</p>
<p>We can begin our analysis in order to address the research question by plotting the possible association between Portuguese and English grades. We shall create a scatterplot to do this, and we create the plot by running the following code and <em>ignoring group (class) membership</em>. In the following chunk of code, I pipe the <code>brazil</code> data using <code>%&gt;%</code> to <code>ggplot()</code> and then create the plot step-by-step, with each step separated by a <code>+</code> except for the last step.</p>
<div class="cell" data-layout-align="center" data-hash="01-multilevel_cache/html/brazil-all_d373e4d635645a523c144e080353680c">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>brazil <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> portuguese, <span class="at">y =</span> english)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Portuguese"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"English"</span>) <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-multilevel_files/figure-html/brazil-all-1.png" class="img-fluid figure-img" style="width:60.0%"></p>
<p></p><figcaption class="figure-caption">Portuguese compared to English grades: each point represents the scores for one child</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Remember that each child ID is associated with a pair of grades: their grade in English and their grade in Portuguese. Each point in Figure @ref(fig:brazil-all) represents the paired grade data for one child.</p>
<p>Because I say that we are interested in predicting English grades then, by convention, we map English grades to the height of the points (i.e.&nbsp;English grade differences are shown as differences on the y-axis). Because we are using Portuguese grades to do the predicting, by convention, we map Portuguese grades to the horizontal position of the points (i.e.&nbsp;Portuguese grade differences are shown as differences on the x-axis).</p>
<p>I have added a line using <code>geom_smooth()</code> in red to indicate the trend of the potential association between variation in Portuguese grades and variation in English grades.</p>
<p>Figure @ref(fig:brazil-all) suggests that children with higher grades in Portuguese tend, on average, to also have higher grades in English.</p>
<section id="exercise-edit-plots" class="level4" data-number="3.9.4.1">
<h4 data-number="3.9.4.1" class="anchored" data-anchor-id="exercise-edit-plots"><span class="header-section-number">3.9.4.1</span> Exercise – edit plots</h4>
<p>Notice that when we write the code to produce the plot, we add arguments to the <code>geom_point()</code> and <code>geom_smooth()</code> function calls to adjust the appearance of the points and the smoother line. Notice, also, that we adjust the labels for the x-axis and y-axis and, finally, that we determine the overall appearance of the plot using the <code>theme_bw()</code> function call.</p>
<p>Do the following exercises to practice your <code>ggplot()</code> skills</p>
<p>Further information to help you try out coding options can be found here (on scatterplots):</p>
<p></p>
<p>and here (on themes):</p>
<p></p>
</section>
</section>
<section id="a-linear-model-ignores-the-multilevel-structure-in-the-data" class="level3" data-number="3.9.5">
<h3 data-number="3.9.5" class="anchored" data-anchor-id="a-linear-model-ignores-the-multilevel-structure-in-the-data"><span class="header-section-number">3.9.5</span> A linear model ignores the multilevel structure in the data</h3>
<p>Our plot indicates the relationship between English and Portuguese language grades, in Figure @ref(fig:brazil-all), ignoring the fact that children in the sample belonged to different classes when they were tested. The plot shows us only information about the children and grades, with each point representing the observed English and Portuguese grades for each <span class="math inline">\(i\)</span> child.</p>
<p>Can we predict variation in English grades given information about children’s Portuguese grades? Are English grades related to Portuguese grades? We can estimate the relationship between English and Portuguese grades using a linear model in which the English grades variable is the <strong>outcome</strong> variable (or the dependent variable) and the Portuguese grades variable is the <strong>predictor</strong> or independent variable:</p>
<span class="math display">\[\begin{equation}
y_i = \beta_0 + \beta_1X_i + e_i
\end{equation}\]</span>
<ul>
<li>where <span class="math inline">\(y_i\)</span> represents the English grade for each <span class="math inline">\(i\)</span> child;</li>
<li><span class="math inline">\(\beta_0\)</span> represents the intercept, the outcome value obtained if values of the explanatory variable are zero;</li>
<li><span class="math inline">\(\beta_1\)</span> represents the effect of variation in <span class="math inline">\(X_i\)</span> the Portuguese grade for each child, with the effect of that variation estimated as the the rate of change in English grade for unit change in Portuguese grade;</li>
<li><span class="math inline">\(e_i\)</span> represents differences, for each child, between the observed English grade and the English grade predicted by the relationship with Portuguese grades.</li>
</ul>
<p>As you have seen, the code for running a linear model corresponds transparently to the statistical model given in the formula.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(english <span class="sc">~</span> portuguese, <span class="at">data =</span> brazil))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = english ~ portuguese, data = brazil)

Residuals:
    Min      1Q  Median      3Q     Max 
-64.909 -17.573   2.782  20.042  53.292 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 29.77780    3.81426   7.807 2.11e-13 ***
portuguese   0.47001    0.07897   5.952 9.91e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 25.02 on 228 degrees of freedom
Multiple R-squared:  0.1345,    Adjusted R-squared:  0.1307 
F-statistic: 35.43 on 1 and 228 DF,  p-value: 9.906e-09</code></pre>
</div>
</div>
<p>The linear model yields the estimate that for unit increase in Portuguese grade there is an associated increase of about .47 in English grade, on average (for the model, <span class="math inline">\(F(1, 228) = 35, p &lt; .001; adj. R^2 = .13\)</span>). So, we have a preliminary answer to our research question.</p>
<p>We shall see that we will need to revise this estimate when we do an analysis that <em>does</em> take school class differences into account.</p>
<section id="code-tip-1" class="level4" data-number="3.9.5.1">
<h4 data-number="3.9.5.1" class="anchored" data-anchor-id="code-tip-1"><span class="header-section-number">3.9.5.1</span> Code tip</h4>
<p>Notice: here, I have dispensed with the creation of a model object by name. The model is estimated anyway, and I have embedded the <code>lm()</code> function call within a <code>summary()</code> function so that I am asking R to do two things:</p>
<ol type="1">
<li><code>lm()</code> fit a linear model</li>
<li><code>summary()</code> print out a summary of the fitted model object</li>
</ol>
<p>I do this to give an example of the way in which code can be varied. Also, to show you how one function can be embedded inside another.</p>
</section>
<section id="exercise-fit-a-different-linear-model" class="level4" data-number="3.9.5.2">
<h4 data-number="3.9.5.2" class="anchored" data-anchor-id="exercise-fit-a-different-linear-model"><span class="header-section-number">3.9.5.2</span> Exercise – fit a different linear model</h4>
<p>Do the following exercises to practice your <code>lm()</code> skills</p>
</section>
</section>
<section id="notation" class="level3" data-number="3.9.6">
<h3 data-number="3.9.6" class="anchored" data-anchor-id="notation"><span class="header-section-number">3.9.6</span> Notation</h3>
<p>In the following discussion, I will present some model formulas as equations. I am not doing that because the discussion is going to consider the modeling in terms of the underlying mathematics. I am doing it with the aim of clarifying how quantities – observed, estimated or predicted – add up, in terms of the linear and then the linear mixed-effects model.</p>
<p>To make it clear that each observation can be understood as part of a complex multilevel or crossed random effects structure, I am going to use indices as subscripts for variables.</p>
<p>Thus, in the Brazilian schools example, we shall see that we are concerned with observations about children’s school grades, where children are sampled as individuals <em>nested</em> in samples of classes. We will examine how an outcome variable (English language grade) is related to a predictor variable (Portuguese language grade) such that:</p>
</section>
<section id="can-we-really-ignore-the-multilevel-structure" class="level3" data-number="3.9.7">
<h3 data-number="3.9.7" class="anchored" data-anchor-id="can-we-really-ignore-the-multilevel-structure"><span class="header-section-number">3.9.7</span> Can we really ignore the multilevel structure?</h3>
<p>The linear model ignores the higher-level structure, the distinction between classes. Does that matter?</p>
<p>We can see the answer to that question if we inspect Figure @ref(fig:pporteng). We create the plot using the following chunk of code; we discuss that later, first reflecting on what the plot shows us.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>brazil <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> portuguese, <span class="at">y =</span> english)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>(<span class="at">colour =</span> <span class="st">"darkgrey"</span>) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">colour =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> class_number) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Portuguese"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"English"</span>) <span class="sc">+</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">25</span>,<span class="dv">50</span>,<span class="dv">75</span>)) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">50</span>,<span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-multilevel_files/figure-html/pporteng-1.png" class="img-fluid figure-img" style="width:150.0%"></p>
<p></p><figcaption class="figure-caption">Plot of child grades, comparing English with Portuguese grades, shown separately for each school class</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Figure @ref(fig:pporteng) presents a different scatterplot to show the relationship between children’s Portuguese and English grades for the children in each different class. We can see that the relationship between Portuguese and English grades is (roughly) similar across classes: in general, children with higher Portuguese grades also tend to have higher English grades. However, Figure @ref(fig:pporteng) makes it obvious that there are important differences between classes. We can see that the slope of the best fit line (shown in black) varies between classes. And we can see that the intercept (where the line meets the y-axis) also varies between classes. Further, we can see that in some classes, there is no relationship or a negative relationship between Portuguese and English grades.</p>
<p>Critically, we can see that classes differ in how much data we have for each. For some classes, we have many observations (e.g., M11) and for other classes we have few or one observation (e.g., M22, with one child). We know, in advance, that variation in sample size will be associated with variation in the uncertainty we have about the estimated relationship between Portuguese and English grades. You will remember that the Central Limit Theorem allows us to calculate the standard error of an estimate like the mean, given the sample size, and that the standard error is an index of our uncertainty of the estimate.</p>
<section id="code-tip-facetting-creating-grids-of-plots" class="level4" data-number="3.9.7.1">
<h4 data-number="3.9.7.1" class="anchored" data-anchor-id="code-tip-facetting-creating-grids-of-plots"><span class="header-section-number">3.9.7.1</span> Code tip – facetting – creating grids of plots</h4>
<p>As you have seen, you can ask <code>ggplot()</code> to print a separate plot for each sub-group in a dataset. To produce Figure @ref(fig:pporteng), we ask for a separate plot of the <span class="math inline">\(english ~ portuguese\)</span> relationship, one plot for each class. Notice that in the code, the key expression is <code>facet_wrap(~ class_number)</code> This means</p>
<p>The production of a grid of plots is a useful method for comparing patterns between data sub-sets or groups.</p>
<p>You can see more information about <code>facet_wrap()</code> here:</p>
<p></p>
</section>
<section id="code-tip-adjusting-scales" class="level4" data-number="3.9.7.2">
<h4 data-number="3.9.7.2" class="anchored" data-anchor-id="code-tip-adjusting-scales"><span class="header-section-number">3.9.7.2</span> Code tip – adjusting scales</h4>
<p>Notice that in these plots I modified the axes, to show x-axis and y-axis ticks at specific locations using scale functions. The tick is the notch or short line where we show the numbers on the axes.</p>
<p>It can be useful to adjust the ticks on axes, where other plot production factors cause crowding of labels.</p>
<p>You can see more information on scales here:</p>
<p></p>
</section>
<section id="exercise-edit-plots-1" class="level4" data-number="3.9.7.3">
<h4 data-number="3.9.7.3" class="anchored" data-anchor-id="exercise-edit-plots-1"><span class="header-section-number">3.9.7.3</span> Exercise – edit plots</h4>
<p>Do the following exercises to practice your skills</p>
</section>
</section>
<section id="linear-models-for-multilevel-data-dealing-with-the-hierarchical-structure" class="level3" data-number="3.9.8">
<h3 data-number="3.9.8" class="anchored" data-anchor-id="linear-models-for-multilevel-data-dealing-with-the-hierarchical-structure"><span class="header-section-number">3.9.8</span> Linear models for multilevel data – dealing with the hierarchical structure</h3>
<p>Figure @ref(fig:pporteng) shows that there is variation between classes in both the average English grade, shown as differences in the y-axis intercept, and the ‘effect’ of Portuguese language skill, shown as differences in the slope of the best fit line for the predicted relationship between Portuguese and English grades. We put ‘effect’ in quotes to signal the fact that we do not wish to assert a causal relation. The interpretation of the results of the linear model assumes those results are valid provided that the observations are independent, among other things. We can see that we cannot make the assumption of independence because individuals in classes with high average English grades are more likely to have higher English grades.</p>
<p>We can represent in our analysis the information we have about hierarchical structure in the data (child within class) by allowing the regression coefficients to vary between groups. We therefore modify the subscripting to take into account the fact that we must distinguish which child <span class="math inline">\(i\)</span> and which class <span class="math inline">\(j\)</span> we are examining, adapting our model to:</p>
<span class="math display">\[\begin{equation}
y_{ij} = \beta_{0j} + \beta_{1j}X_{ij} + e_{ij}
\end{equation}\]</span>
</section>
<section id="two-step-or-slopes-as-outcomes-linear-models-as-approximations-to-the-linear-mixed-effects-or-multilevel-modeling-approach" class="level3" data-number="3.9.9">
<h3 data-number="3.9.9" class="anchored" data-anchor-id="two-step-or-slopes-as-outcomes-linear-models-as-approximations-to-the-linear-mixed-effects-or-multilevel-modeling-approach"><span class="header-section-number">3.9.9</span> Two-step or slopes-as-outcomes linear models as approximations to the Linear Mixed-effects or Multilevel modeling approach</h3>
<p>In practice, we could capture the variation between classes by performing a <strong>two-step analysis</strong>.</p>
<ul>
<li>First, we estimate the coefficient of the ‘Portuguese’ effect for each class analysed separately.</li>
<li>Second, we can take those per-class coefficients as the outcome variable in a ‘slopes-as-outcomes analysis’ to examine if the per-class estimates of the experimental effect are reliably different from zero or, more usefully, if the per-class estimates vary in relation to some explanatory variable like teacher skill.</li>
</ul>
<p>The problem with the approach is apparent in Figure @ref(fig:pointclass). Figure @ref(fig:pointclass) shows the estimated intercept and coefficient of the slope of the ‘Portuguese’ effect for each class, when we have analyzed the data for each class in a separate linear model. The estimate for each class is shown as a black dot. The standard error of the estimate is shown as a black vertical line, shown above and below a point. You can say that where there is a longer line there we have more uncertainty about the location of the estimate.</p>
<p>The critical point is that <strong>the standard errors vary</strong> a lot between classes. In some classes, the standard error is small (the black line is short) so we can maybe have more certainty over the estimated intercept or slope for those classes. In other classes, the standard error is large (the black line is long) so we can maybe have less certainty over the estimated intercept or slope for those classes. The <strong>key idea</strong> here is that standard errors vary widely between classes but the two-step modeling approach, while it can take into account the between-class differences in estimates, cannot account for the variation in the standard errors about those estimates.</p>
<section id="code-tip-2" class="level4" data-number="3.9.9.1">
<h4 data-number="3.9.9.1" class="anchored" data-anchor-id="code-tip-2"><span class="header-section-number">3.9.9.1</span> Code tip</h4>
<p>Notice that the code I used fits a separate model for each class, and then plots the per-class estimates of intercepts and slopes of the <span class="math inline">\(english \sim portuguese\)</span> relationship. You can check out the code for yourself in the <strong>how-to.R</strong> for this week.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-multilevel_files/figure-html/pointclass-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<p></p><figcaption class="figure-caption">Plot showing the estimated intercept and coefficient of the slope of the Portuguese effect for each class analysed separately</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01-multilevel_files/figure-html/pointclass-2.png" class="img-fluid figure-img" style="width:50.0%"></p>
<p></p><figcaption class="figure-caption">Plot showing the estimated intercept and coefficient of the slope of the Portuguese effect for each class analysed separately</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="discussion-slopes-as-outcomes-analyses-as-a-common-approach" class="level4" data-number="3.9.9.2">
<h4 data-number="3.9.9.2" class="anchored" data-anchor-id="discussion-slopes-as-outcomes-analyses-as-a-common-approach"><span class="header-section-number">3.9.9.2</span> Discussion: slopes-as-outcomes analyses as a common approach</h4>
<p>The ‘slopes-as-outcomes’ approach is quite common and can be found in a number of papers in the psychological and educational research literatures, e.g., in Balota et al.’s (2004) of the analysis of psycholinguistic effects in older and younger adults. Balota et al.&nbsp;(2004) wanted to examine if or how effects of variables like word frequency, on reading response latencies, were different in different age groups. To do this, they first estimated the effect of the (word-level) psycholinguistic variables in separate linear model (multple regressions) for each adult. They then took the estimated coefficients as the dependent variable (slopes-as-outcomes) for a second analysis in which they tested the effect of age group on variation in the estimated coefficients (see Lorch &amp; Myers, 1990, for a discussion of the approach).</p>
<p>You may be asked to do this. I would advise you against it because there is a better way, as we see next.</p>
</section>
</section>
<section id="multilevel-models" class="level3" data-number="3.9.10">
<h3 data-number="3.9.10" class="anchored" data-anchor-id="multilevel-models"><span class="header-section-number">3.9.10</span> Multilevel models</h3>
<p>Multilevel models incorporate estimates of the intercept and the effect of independent (experimental or correlational) variables plus estimates of the random variation between classes in intercepts and slopes. Multilevel models are also known as <strong>mixed-effects models</strong> because they involve the estimation of <strong>fixed effects</strong> (effects due to independent variables) and <strong>random effects</strong> (effects due to random differences between groups).</p>
<p>We model the intercept (varying between classes) as:</p>
<span class="math display">\[\begin{equation}
\beta_{0j} = \gamma_0 + U_{0j}
\end{equation}\]</span>
<p>We model the coefficient of the (Portuguese language) skill effect as:</p>
<span class="math display">\[\begin{equation}
\beta_{1j} = \gamma_1 + U_{1j}
\end{equation}\]</span>
<p>These models can then be combined:</p>
<span class="math display">\[\begin{equation}
y_{ij} = \gamma_0 + \gamma_1X_{ij} + U_{0j} + U_{1j}X_{ij} + e_{ij}
\end{equation}\]</span>
<p>such that the English grade observed for each child <span class="math inline">\(y_{ij}\)</span> can be predicted given:</p>
</section>
<section id="how-should-we-think-about-the-differences-between-the-classes" class="level3" data-number="3.9.11">
<h3 data-number="3.9.11" class="anchored" data-anchor-id="how-should-we-think-about-the-differences-between-the-classes"><span class="header-section-number">3.9.11</span> How should we think about the differences between the classes?</h3>
<p>If you have had some experience analyzing psychological data, then there is a potential approach to thinking about the effect of the differences between classes that would seem natural. We could seek to estimate the relationship of interest – here, the association between English and Portuguese grades – while also estimating the relationship between (outcome) English grades and the impact made by what class a child is in. If you think back to, say, Figure @ref(fig:SB12multistage), then you could imagine how it would make sense to create a factor variable to code for class, and to then specify a model in which English grades are the outcome and Portuguese grade and also class are the predictors. This approach has, in fact, been proposed (see e.g.&nbsp;Lorch &amp; Myers, 1990).</p>
<p>In this approach, we would construct a model in which we have English grades as the outcome variable, Portuguese grades as one predictor variable, and then add a variable to code for class identity. The ‘effect’ of the class variable would then capture the differences in intercepts between classes. You could add a further variable to code for differences between classes in the slope of the relationship between English and Portuguese grades, i.e., to allow for the fact that the relationship is positive or negative, stronger or weaker, in different classes. If we added that further variable to code for differences between classes in the English-Portuguese relationship, then we would be estimating those differences as <em>interactions</em> between (1.) the predictive ‘effect’ of Portuguese grades on English grades and (2.) the class effect. An interaction effect is what we have when the effect of one variable (the predictive ‘effect’ of Portuguese grades) is different for different levels of the other variable (the predictive ‘effect’ of Portuguese grades is different for different classes).</p>
<p>Thinking about this approach helps us to think about what we are doing when we are working with multilevel structured data. But the problem with this approach is that it does not allow us to generalize beyond the sample we have. The estimates we would have, given a model in which we code directly for class, would tell us only about the classes in our sample.</p>
<p>Most of the time, we would prefer to do analyses whose results could be generalized: to other children, to other classes. For this reason, it makes more sense to suppose that <span class="math inline">\(U_{0j} + U_{1j}\)</span>, the class-level deviations, are unexplained differences drawn at random from a population of potential class differences. What does this mean?</p>
<p>Think back to your understanding of the linear model. You have learnt that when we fit a linear model like <span class="math inline">\(y_i = \beta_0 + \beta_1X_i + e_i\)</span> we include a term <span class="math inline">\(e_i\)</span> to represents the differences, for each child, between the <em>observed</em> (outcome) English grade and the English grade <em>predicted</em> by the relationship with Portuguese grades. Those differences between observed and predicted outcomes are called <strong>residuals</strong>. We assume that the direction and size of any one residual, for any one child, is randomly determined because we typically have no idea why there might be a big difference between the predicted and observed grade for one child but a small residual difference for another.</p>
<p>Now, we can imagine that there will be many classes in many schools, and we can surely expect that there will be differences between the classes. These differences will result from plenty of factors we do not measure or cannot explain. Indeed, we have seen that there are differences between the average (outcome) English grade i.e.&nbsp;the <em>predicted</em> intercept and the observed intercept for each class, and we have seen that there are differences between the average slope of the English-Portuguese grades relationship i.e.&nbsp;the <em>predicted</em> slope and the slope for each class. These differences would, in effect, be <em>random differences</em>. And we can see how the variation in these differences are, for us, just a kind of random error variance, which we can see as <strong>class-level residuals</strong>.</p>
<p>We suppose, technically, that the differences between classes, controlling for the effect of the explanatory variable, are exchangeable (it does not matter which class is which), with classes varying at random. Multilevel models incorporate estimation of the explanatory variables effects <span class="math inline">\(\gamma_0 + \gamma_1\)</span> accounting for group-level error variance <span class="math inline">\(U_{0j} + U_{1j}\)</span>.</p>
<p>The difference between the two-step approach and the multilevel modelling approach is this. In the two-step approach, seen earlier, we estimate – separately, for each class – the intercept and the slope of the Portuguese effect, using <em>just the data for that class</em> and ignoring the data for other classes. In the multilevel model, in contrast, we use all the observations, estimating the average intercept and the average slope of the Portuguese effect <em>plus the variance</em> due to the difference for each class (1.) between the average intercept and the class intercept or (2.) between the average slope and the class slope. We can understand these differences between the average (intercept or class) and the class differences as class-level residuals <span class="math inline">\(U_{0j} + U_{1j}\)</span> in addition to the child-level residuals <span class="math inline">\(e_{ij}\)</span>. This leads us to a conclusion that represents a critical way to understand multilevel models.</p>
</section>
<section id="fitting-a-multilevel-model-using-the-lmer-function" class="level3" data-number="3.9.12">
<h3 data-number="3.9.12" class="anchored" data-anchor-id="fitting-a-multilevel-model-using-the-lmer-function"><span class="header-section-number">3.9.12</span> Fitting a multilevel model using the lmer() function</h3>
<p>We can fit a multilevel model of the <span class="math inline">\(english \sim portuguese\)</span> relationship, taking into account the fact that the pupils tested in the study were recruited from different classes, using the convenient and powerful <code>lmer()</code> function. Happily, the code we use to define a model in <code>lmer()</code> is much like the code we use to define a model in <code>lm()</code> with <em>one important difference</em> which I shall explain.</p>
<p>Let’s try it out.</p>
<p>To use the <code>lmer()</code> function you need to make the <code>lme4</code> library available.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The model you are going to code will correspond to the statistical model that we have been discussing:</p>
<span class="math display">\[\begin{equation}
y_{ij} = \gamma_0 + \gamma_1X_{ij} + U_{0j} + U_{1j}X_{ij} + e_{ij}
\end{equation}\]</span>
<p>And the code is written as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>porto.lmer1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(english <span class="sc">~</span> portuguese <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                              (portuguese <span class="sc">+</span> <span class="dv">1</span><span class="sc">|</span>class_number),</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                              <span class="at">data =</span> brazil)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can see that the <code>lmer()</code> function call is closely similar to the <code>lm()</code> function call, with one critical exception, as I explain next.</p>
<p>First, we have a chunk of code mostly similar to what we do when we do a regression analysis.</p>
<p>Second, we have a bit that is specific to multilevel or mixed-effects models.</p>
<p>If you run the model code as written – see the .R file for an example of the code – and it works then the code will be shown in the console window in R-Studio. To show the model results, you need to get a summary of the model, using the model name.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(porto.lmer1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="exercise-fitting-linear-mixed-effects-models" class="level4" data-number="3.9.12.1">
<h4 data-number="3.9.12.1" class="anchored" data-anchor-id="exercise-fitting-linear-mixed-effects-models"><span class="header-section-number">3.9.12.1</span> Exercise – fitting linear mixed-effects models</h4>
<p>Mixed-effects model code is hard to get used to <em>at first</em>. A bit of practice helps to show you which bits of code are important, and which bits you will change for your own analyses</p>
<p>Try out these variations and <em>look carefully</em> at the different results.</p>
</section>
</section>
<section id="reading-the-lmer-results" class="level3" data-number="3.9.13">
<h3 data-number="3.9.13" class="anchored" data-anchor-id="reading-the-lmer-results"><span class="header-section-number">3.9.13</span> Reading the <em>lmer</em> results</h3>
<p>Now let’s take a look at the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(porto.lmer1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: english ~ portuguese + (portuguese + 1 | class_number)
   Data: brazil

REML criterion at convergence: 2104.3

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.81321 -0.59584  0.04359  0.60018  2.23722 

Random effects:
 Groups       Name        Variance Std.Dev. Corr 
 class_number (Intercept) 341.4803 18.479        
              portuguese    0.3295  0.574   -0.98
 Residual                 493.1009 22.206        
Number of obs: 230, groups:  class_number, 18

Fixed effects:
            Estimate Std. Error t value
(Intercept)  25.2837     6.2669   4.034
portuguese    0.6590     0.1729   3.811

Correlation of Fixed Effects:
           (Intr)
portuguese -0.943</code></pre>
</div>
</div>
<p>Notice that the output has a number of elements.</p>
<p>Note that we see coefficient estimates like in a linear model summary <strong>but no p-values</strong>. We will come back to p-values later but note that their absence is not a bug. Note also that we do not see an <span class="math inline">\(R^2\)</span> estimate. We will come back to that too.</p>
<section id="exercise-how-do-we-report-mixed-effects-models-results" class="level4" data-number="3.9.13.1">
<h4 data-number="3.9.13.1" class="anchored" data-anchor-id="exercise-how-do-we-report-mixed-effects-models-results"><span class="header-section-number">3.9.13.1</span> Exercise – How do we report mixed-effects models results?</h4>
<p>There is no convention, yet, on how to report the results of these models. Lotte Meteyard and I argue for a set of conventions that will help researchers to understand each others’ results better: check out the bit where we advise Psychologists how to write about the results, in our paper (Meteyard &amp; Davies, 2020).</p>
</section>
</section>
<section id="fixed-and-random-effects" class="level3" data-number="3.9.14">
<h3 data-number="3.9.14" class="anchored" data-anchor-id="fixed-and-random-effects"><span class="header-section-number">3.9.14</span> Fixed and random effects</h3>
<p>You will have noticed the reference to fixed and random effects in the discussion in this chapter, and the use of fixed and random effects as titles for sections of the model output. The terms <em>fixed effects</em> and <em>random effects</em> are not used consistently in the statistical literature (Gelman &amp; Hill, 2007). I am going to use these terms because they are helpful, at first, and because they are widely used, not least in the results of our analyses in R.</p>
<p>It is common in the psychological literature to refer to the effects on outcomes of experimental manipulations (e.g., the effect on outcomes of differences between experimental conditions) or to the effects of correlated variables of theoretical or explanatory interest (e.g., the effect of differences in Portuguese language skill) as <em>fixed effects</em>. Typically, we are aiming to get estimates of the coefficients of these effects. And, much like we would do when we use linear models, we expect that these coefficients represent an estimate of the effects of these variables, on average, across the population. (Hence, some analysts prefer to talk about these effects as population average effects).</p>
<p>In comparison, when we are thinking about the effects on outcomes of what we understand to be the random differences between sampled children (e.g., the child-level residuals) or the random differences between sampled classes (e.g., the class-level residuals) then we refer to these effects as <em>random effects</em>. As we have seen, we usually estimate random effects as variances and can estimate them as random error variances. While we may care to estimate how differences in, say, Portuguese language score, is associated with English grade, we typically do not care about the impact of the specific difference between any two classes in English grade.</p>
<p>However, if you take your education in this area further, you will find that the way that fixed and random effects are talked about in the statistical literature can be, at best, inconsistent. And, ultimately, you might ask yourself if there are principled distinctions between fixed and random effects. We can leave these problems aside, here, because they do not influence how we shall learn and practice using multilevel models in the early to medium term in our development of skills and understanding.</p>
</section>
<section id="is-there-a-difference-between-linear-model-and-linear-mixed-effects-model-results" class="level3" data-number="3.9.15">
<h3 data-number="3.9.15" class="anchored" data-anchor-id="is-there-a-difference-between-linear-model-and-linear-mixed-effects-model-results"><span class="header-section-number">3.9.15</span> Is there a difference between linear model and linear mixed-effects model results?</h3>
<p>Recall that the linear model yields the estimate that for unit increase in Portuguese grade there is an associated .5 increase in English grade, on average (<span class="math inline">\(F(1, 228) = 35, p &lt; .001; adj. R^2 = .13\)</span>). We can see that the estimate of the effect <strong>for the mixed-effects model</strong> is <span class="math inline">\(\beta = .659\)</span> which is somewhat different from the effect estimate we got from the linear model.</p>
</section>
</section>
<section id="conclusions" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="conclusions"><span class="header-section-number">3.10</span> Conclusions</h2>
<p>Psychological studies frequently result in hierarchically structured data. The structure can be understood in terms of the grouping of observations, as when there are multiple observations per group, participant or stimulus. The existence of such structure must be taken into account in analyses. Multilevel or mixed-effects models can be specified by the researcher to include random effects parameters that capture unexplained differences between participants or other sampling units in the intercepts or the slopes of explanatory variables. Where a sample of participants is asked to respond to a sample of stimuli, structure relating both to participants and to stimuli can be incorporated.</p>
<p>Many researchers will be aware of concerns over the non-replication of published effects in psychological science (Pashler &amp; Wagenmakers, 2012). As Gelman (2014) discusses, non-replication of results may arise if effects vary between contexts groups while traditional analytic methods assume that effects are constant. Psychological researchers can expect average outcomes and the effects of independent variables to vary among sampling units, whether their investigations involve multiple observations per child or stimulus, or children sampled within classes, clinics or schools. However, traditional analytic methods often require us to ignore this variation by averaging, say, responses over multiple trials for each child, to collapse an inherently multilevel data structure into a single level of observations that can be analysed using regression or ANOVA. By using multilevel models, researchers will, instead, be able to properly estimate the effects of theoretical interest, and better understand how those effects vary.</p>
<section id="summary" class="level3" data-number="3.10.1">
<h3 data-number="3.10.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">3.10.1</span> Summary</h3>
<p>We outlined the features of a structure dataset. We then discussed visualizing and modeling the relationship between outcome and predictor variables:</p>
</section>
<section id="useful-functions" class="level3" data-number="3.10.2">
<h3 data-number="3.10.2" class="anchored" data-anchor-id="useful-functions"><span class="header-section-number">3.10.2</span> Useful functions</h3>
<p>We used functions to read-in the libraries of functions we needed.</p>
<p>We used some new functions, or focused on functions we have seen before but not discussed</p>
<p>We used the function to get model results for both linear models and for the mulilevel or liner mixed-effects model.</p>
</section>
</section>
<section id="r-code-and-data-file-access-for-the-class" class="level2" data-number="3.11">
<h2 data-number="3.11" class="anchored" data-anchor-id="r-code-and-data-file-access-for-the-class"><span class="header-section-number">3.11</span> R code and data file access for the class</h2>
<p>Activities in the class that goes with this chapter are associated with the following data file and .R code file:</p>
<p>These files are located in a .zip folder called <code>PSYC402-01-multilevel-resources</code>.</p>
<p>Go to the 402 Moodle folder for week 16, find and download the <code>PSYC402-01-multilevel-resources</code> folder from:</p>
<p></p>
<p>Run the code in the .R file to reproduce the results presented in this chapter and in accompanying the slides.</p>
</section>
<section id="references" class="level2" data-number="3.12">
<h2 data-number="3.12" class="anchored" data-anchor-id="references"><span class="header-section-number">3.12</span> References</h2>
<section id="sec-multi-reading" class="level3" data-number="3.12.1">
<h3 data-number="3.12.1" class="anchored" data-anchor-id="sec-multi-reading"><span class="header-section-number">3.12.1</span> Recommended reading</h3>
<p>Snijders and Bosker (2012) present a helpful overview of multilevel modelling. Readers familiar with the book will see that I rely on it to construct the formal presentation of the models.</p>
<p>Baayen et al.&nbsp;(2008; see, also, Barr et al., 2013; Judd et al., 2012) discuss mixed-effects models with crossed random effects. This is the topic we shall discuss next.</p>
<p>I wrote a tutorial article on mixed-effects models with Lotte Meteyard. We discuss how important the approach now is for psychological science, what researchers worry about when they use it, and what they should do and report when they use the method/</p>
<p>Meteyard, L., &amp; Davies, R.A.I. (2020). Best practice guidance for linear mixed-effects models in psychological science, <em>Journal of Memory and Language</em>, 112, 104092, </p>
</section>
<section id="references-list" class="level3" data-number="3.12.2">
<h3 data-number="3.12.2" class="anchored" data-anchor-id="references-list"><span class="header-section-number">3.12.2</span> References list</h3>
<p>Baayen, R. H., Davidson, D. J., &amp; Bates, D. M. (2008). Mixed-effects modeling with crossed random effects for subjects and items. <em>Journal of Memory and Language</em>, 59, 390-412.</p>
<p>Balota, D. A., Cortese, M. J., Sergent-Marshall, S. D., Spieler, D. H., &amp; Yap, M. J. (2004). Visual word recognition of single-syllable words. <em>Journal of Experimental Psychology: General</em>, 133(2), 283.</p>
<p>Barr, D. J., Levy, R., Scheepers, C., &amp; Tily, H. J. (2013). Random effects structure for confirmatory hypothesis testing: Keep it maximal. <em>Journal of Memory and Language</em>, 68, 255-278.</p>
<p>Bryk, A. S., &amp; Raudenbush, S. W. (1992). . London, UK: Sage.</p>
<p>Gelman, A. (2014). The Connection Between Varying Treatment Effects and the Crisis of Unreplicable Research: A Bayesian Perspective. <em>Journal of Management</em>, DOI: 0149206314525208.</p>
<p>Gelman, A., &amp; Hill, J. (2007). <em>Data analysis using regression and multilevel/hierarchical models.</em> Cambridge University Press.</p>
<p>Goldstein, H. (2011). . London, UK: John Wiley &amp; Sons.</p>
<p>Golino, H.F. &amp; Gomes, C.M.A. (2014). Psychology data from the “BAFACALO project: The Brazilian Intelligence Battery based on two state-of-the-art models – Carroll’s Model and the CHC model”. <em>Journal of Open Psychology Data</em>, 2(1): e6, DOI: </p>
<p>Judd, C. M., Westfall, J., &amp; Kenny, D. A. (2012). Treating stimuli as a random factor in social psychology: a new and comprehensive solution to a pervasive but largely ignored problem. <em>Journal of Personality and Social Psychology</em>, 103, 54.</p>
<p>Kreft, I., &amp; de Leeuw, J. (1998). . London, UK: Sage.</p>
<p>Lorch, R. F., Jr., &amp; Myers, J. L. (1990). Regression analyses of repeated measures data in cognitive research. <em>Journal of Experimental Psychology: Learning, Memory, and Cognition</em>, 16, 149–157. http://dx.doi.org/ 10.1037/0278-7393.16.1.149</p>
<p>Pashler, H., &amp; Wagenmakers, E. J. (2012). Editors’ Introduction to the Special Section on Replicability in Psychological Science A Crisis of Confidence? <em>Perspectives on Psychological Science</em>, 7, 528-530.</p>
<p>Snijders, T.A., &amp; Bosker, R.J. (2012). <em>Multilevel analysis (2nd Edition)</em>. London, UK: Sage.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="doc-bibliography" style="display: none">
<div id="ref-Baayen2008" class="csl-entry" role="doc-biblioentry">
Baayen, R. H., Davidson, D. J., &amp; Bates, D. M. (2008). Mixed-effects modeling with crossed random effects for subjects and items. <em>Journal of Memory and Language</em>, <em>59</em>(4), 390–412. <a href="https://doi.org/10.1016/j.jml.2007.12.005">https://doi.org/10.1016/j.jml.2007.12.005</a>
</div>
<div id="ref-golino2014" class="csl-entry" role="doc-biblioentry">
Golino, H., &amp; Gomes, C. (2014). Psychology data from the <span>“</span>BAFACALO project: The Brazilian Intelligence Battery based on two state-of-the-art models <span></span> Carroll<span>’</span>s Model and the CHC model<span>”</span>. <em>Journal of Open Psychology Data</em>, <em>2</em>(1), e6. <a href="https://doi.org/10.5334/jopd.af">https://doi.org/10.5334/jopd.af</a>
</div>
<div id="ref-kreft1998" class="csl-entry" role="doc-biblioentry">
Kreft, I., &amp; Leeuw, J. de. (1998). <em>Introducing multilevel modeling</em> (D. Wright, Ed.). Sage Publications.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./visualization.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data visualization</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./02-mixed.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Introduction to linear mixed-effects models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>